[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 20
  
[build.environment]
NODE_VERSION = "18"

[build.cache]
  paths = ["node_modules/**", "package-lock.json"]
