[build]
publish = "dist"
command = "npm run build"
branch = "refs/heads/main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 20
  
[build.environment]
NODE_VERSION = "18"

[build.cache]
<<<<<<< HEAD
  paths = ["node_modules/**", "package-lock.json"]
=======
  paths = ["node_modules/**", "package-lock.json"]
>>>>>>> 0d2753a565da61d5a5fe2b4042be02b8d76c4582
